# Generated by Django 5.1.2 on 2024-11-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admissionNumber',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
